language: ruby
rvm:
- 2.4.2

before_script:
 - chmod +x ./script/*
 - gem update --system 2.6.11
 - gem --version
 - gem install bundler

script:
 - ./script/cibuild.sh
 - ./script/cideploy.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
