---

openshift_cluster_content:
- object: projectrequest
  content:
  - name: "Projects"
    file: "{{ inventory_dir }}/../projects/projects-prod.yml"
    file_action: create
- object: policy
  content_dir: "{{ inventory_dir }}/../policy"
- object: deployments
  content:
  - name: "dev-deployment"
    template: "{{ inventory_dir }}/../deploy/template.yml"
    params: "{{ inventory_dir }}/../deploy/prod/params"
